-- ============================================
-- PAYMENT LINKS TABLE (Complete Schema)
-- ============================================

-- Create payment_links table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.payment_links (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  provider text NOT NULL,
  amount numeric NOT NULL,
  description text,
  payment_url text NOT NULL,
  external_id text, -- ID do link no provedor externo
  slug text UNIQUE, -- Short slug for custom domain links
  clicks integer DEFAULT 0, -- Click counter
  last_clicked_at timestamp with time zone, -- Last click timestamp
  status text DEFAULT 'active' CHECK (status IN ('active', 'paid', 'expired', 'cancelled')),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
  expires_at timestamp with time zone
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_payment_links_user_id ON public.payment_links(user_id);
CREATE INDEX IF NOT EXISTS idx_payment_links_slug ON public.payment_links(slug);
CREATE INDEX IF NOT EXISTS idx_payment_links_status ON public.payment_links(status);

-- Enable Row Level Security
ALTER TABLE public.payment_links ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if they exist
DROP POLICY IF EXISTS "Users can view their own payment links" ON public.payment_links;
DROP POLICY IF EXISTS "Users can create their own payment links" ON public.payment_links;
DROP POLICY IF EXISTS "Users can update their own payment links" ON public.payment_links;
DROP POLICY IF EXISTS "Users can delete their own payment links" ON public.payment_links;

-- RLS Policies
CREATE POLICY "Users can view their own payment links"
  ON public.payment_links
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own payment links"
  ON public.payment_links
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own payment links"
  ON public.payment_links
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own payment links"
  ON public.payment_links
  FOR DELETE
  USING (auth.uid() = user_id);

-- Add comments
COMMENT ON TABLE public.payment_links IS 'Payment links generated by users';
COMMENT ON COLUMN public.payment_links.slug IS 'Unique short slug for custom domain links (e.g., ABC123)';
COMMENT ON COLUMN public.payment_links.clicks IS 'Number of times this payment link was clicked';
COMMENT ON COLUMN public.payment_links.last_clicked_at IS 'Timestamp of the last click on this link';
